// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARKTSDN5DBK3VaYq8xUt8qxUmO9OOni7w',
    appId: '1:1078386198823:web:ae607b4cb3a1aa86ef4102',
    messagingSenderId: '1078386198823',
    projectId: 'myapp-f449e',
    authDomain: 'myapp-f449e.firebaseapp.com',
    storageBucket: 'myapp-f449e.appspot.com',
    measurementId: 'G-Z5NLHRJHD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIB7mwj_rdcZMXohR9wnU-VX71aW_fDmM',
    appId: '1:1078386198823:android:783d627c6057f48bef4102',
    messagingSenderId: '1078386198823',
    projectId: 'myapp-f449e',
    storageBucket: 'myapp-f449e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5WCjmuAjRfA89GnDNrAOa8a4pmOhQdI',
    appId: '1:1078386198823:ios:33dbc9b0c5a5d2b8ef4102',
    messagingSenderId: '1078386198823',
    projectId: 'myapp-f449e',
    storageBucket: 'myapp-f449e.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5WCjmuAjRfA89GnDNrAOa8a4pmOhQdI',
    appId: '1:1078386198823:ios:33dbc9b0c5a5d2b8ef4102',
    messagingSenderId: '1078386198823',
    projectId: 'myapp-f449e',
    storageBucket: 'myapp-f449e.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARKTSDN5DBK3VaYq8xUt8qxUmO9OOni7w',
    appId: '1:1078386198823:web:19c1b66a186d8eadef4102',
    messagingSenderId: '1078386198823',
    projectId: 'myapp-f449e',
    authDomain: 'myapp-f449e.firebaseapp.com',
    storageBucket: 'myapp-f449e.appspot.com',
    measurementId: 'G-008K9MELL2',
  );

}